apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ee5upa4y4-dotnet-basic
  janus-idp.io/tekton: ee5upa4y4-dotnet-basic
  backstage.io/kubernetes-id: ee5upa4y4-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ee5upa4y4-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
